language: python
dist: xenial
python:
  - "3.6"
  - "3.7.1"
install:
  - pip install -U pip==18.0 pipenv==2018.7.1
  - pipenv install --system --deploy --ignore-pipfile --dev
  - pipenv run pip install -e .
script: pipenv run test && pipenv run lint && pipenv run format-check
after_success:
  - codecov
