image: python:3.5

pipelines:
  default:
    - step:
        script:
          - python --version
          - pip --version
          - pip install -r requirements.txt
          - pip install -r requirements-dev.txt
          - coverage run --source="easyqueue" --omit="easyqueue/tests/*" -m unittest discover -v
          - coverage report -m
