image: python:3.6

pipelines:
  default:
    - step:
        script:
          - python --version
          - pip --version
          - pip install -r requirements-dev.txt
          - py.test --cov=easyqueue

