version: '3'

services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - ./docker/data/:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  asyncworker:
    hostname: asyncworker
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
#      todo: adicionar volumes