image: python:3.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python --version
          - pip --version
          - pip install -r requirements-dev.txt
          - py.test --cov=easyqueue
  branches:
      master:
        - step:
            caches:
                - pip
            script:
              - pip install -r requirements-dev.txt
              - py.test
              - bash ./deploy.sh
