{
 "title": "Metrics example",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(asyncworker_request_counter_total{instance=~\"$instance\"}[$__interval])\n",
     "legendFormat": "{{url}}"
    }
   ]
  },
  { "title": "Counter example", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last value",
   "type": "stat",
   "description": "last value of a_counter metric",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asyncworker_a_counter_total{instance=~\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Counts per minute",
   "type": "graph",
   "description": "Number of times the GET /count route was called per minute",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(asyncworker_a_counter_total{instance=~\"$instance\"}[$__interval])\n",
     "legendFormat": "Increments"
    }
   ]
  }
 ]
}